### ISSUE TITLE
(exwm-evil-enable-mouse-workaround) obsolete?

### ISSUE THREAD

**Issue by theconsciouspasticcio** [LemonBreezes/exwm-evil#1]
Hi, I noticed after a doom-upgrade that you removed the mouse hack, but I still have the same problem that mouse clicks do not work unless in insert-mode. What do you suggest? What made the hack obsolete?

**Comment by LemonBreezes** [comment]
> Hi, I notice after a doom-upgrade that you removed the mouse hack, but I still have the same problem that mouse clicks do not work unless in insert-mode. What do you suggest? What made the hack obsolete?

Have you updated EXWM? The mouse hack was merged into EXWM so there was no longer a reason to have it in this package.

**Comment by LemonBreezes** [comment]
> Hi, I notice after a doom-upgrade that you removed the mouse hack, but I still have the same problem that mouse clicks do not work unless in insert-mode. What do you suggest? What made the hack obsolete?

I just added a different workaround for this issue. Now when you click, it automatically enters insert state and sends the click to the window. This doesn't allow you to drag the mouse directly from normal state but it's good to at least be able to click again.

If anyone comes up with an alternate fix that allows dragging, please follow up.

**Comment by LemonBreezes** [comment]
> Hi, I notice after a doom-upgrade that you removed the mouse hack, but I still have the same problem that mouse clicks do not work unless in insert-mode. What do you suggest? What made the hack obsolete?

By the way, do you use Doom Emacs or Persp Mode? I have a workaround for EXWM not gaining focus when switching to workspaces with EXWM buffers.
